/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        'bg-deep': '#0d0907',
        'bg-surface': '#1a110d',
        'bg-elevated': '#241810',
        'surface': '#181307',
        'surface-dim': '#181307',
        'surface-container': '#251f12',
        'surface-container-low': '#201b0f',
        'surface-container-high': '#2f291c',
        'surface-container-highest': '#3b3426',
        'surface-variant': '#3b3426',
        'on-surface': '#ede1cd',
        'on-surface-variant': '#d3c4b1',
        'outline': '#9c8f7d',
        'outline-variant': '#4f4537',
        'primary': '#f5bd5d',
        'on-primary': '#432c00',
        'primary-container': '#d4a043',
        'gold': '#c9a84c',
        'brass': '#b87333',
        'amber-bright': '#f5a623',
        'amber-dim': '#8a6420',
        'danger-deep': '#8b1a1a',
        'danger': '#e94560',
        'table-felt': '#1f4433',
        'card-face': '#f5f0e8',
        'card-back': '#4a1a1a',
        'text-muted': '#7a6a5a',
        'text-address': '#9a8a7a',
        'coming-soon': '#6b5b95',
        'secondary': '#abcfb8',
        'on-secondary': '#163627',
        'error': '#ffb4ab',
      },
      fontFamily: {
        'display': ['Playfair Display', 'serif'],
        'body': ['Lora', 'serif'],
        'stamp': ['Bebas Neue', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
      },
    },
  },
  plugins: [],
};
